# Generated by Django 5.2.7 on 2025-11-01 16:37

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 60 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This may contain only letters, numbers, and @/./+/-/_ characters.', 'invalid')], verbose_name='username')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=40, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('feedback_type', models.CharField(choices=[('general', 'General Suggestion'), ('profile_issue', 'Profile Issue'), ('success_story', 'Success Story'), ('other', 'Other')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], help_text='Optional rating for Vivah platform', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mobile', models.CharField(max_length=15)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=accounts.models.user_premium_upload_path)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_image_upload_path)),
                ('user_identity', models.CharField(db_index=True, default=accounts.models.key_generator, editable=False, max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('marital_status', models.CharField(choices=[('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Awaiting Divorce', 'Awaiting Divorce')], default='Never Married', max_length=30)),
                ('religion', models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Jain', 'Jain'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=50, null=True)),
                ('caste', models.CharField(blank=True, choices=[('Bania', 'Bania'), ('Barhai', 'Barhai (Carpenter)'), ('Beldar', 'Beldar'), ('Bhuiya', 'Bhuiya'), ('Bind', 'Bind'), ('Brahmin', 'Brahmin'), ('Bhumihar', 'Bhumihar'), ('Chamar', 'Chamar'), ('Chaurasia', 'Chaurasia'), ('Dhobi', 'Dhobi (Washerman)'), ('Dom', 'Dom'), ('Dusadh', 'Dusadh (Paswan)'), ('Gupta', 'Gupta'), ('Halwai', 'Halwai (Sweet Maker)'), ('Kahar', 'Kahar'), ('Kalwar', 'Kalwar'), ('Kanu', 'Kanu'), ('Kayastha', 'Kayastha'), ('Kewat', 'Kewat'), ('Koeri', 'Koeri'), ('Kumhar', 'Kumhar'), ('Kurmi', 'Kurmi'), ('Kushwaha', 'Kushwaha'), ('Lohar', 'Lohar (Blacksmith)'), ('Mali', 'Mali (Gardener)'), ('Majhi', 'Majhi'), ('Mallah', 'Mallah (Nishad)'), ('Musahar', 'Musahar'), ('Nai', 'Nai (Barber)'), ('Nonia', 'Nonia'), ('Pandit', 'Pandit'), ('Pasi', 'Pasi'), ('Patwa', 'Patwa'), ('Rajak', 'Rajak'), ('Rajput', 'Rajput'), ('Ranchi', 'Ranchi'), ('Ravidas', 'Ravidas'), ('Sahu', 'Sahu'), ('Saw', 'Saw'), ('Sonar', 'Sonar (Goldsmith)'), ('Sutar', 'Sutar'), ('Swarnkar', 'Swarnkar'), ('Tanti', 'Tanti'), ('Tatwa', 'Tatwa'), ('Teli', 'Teli'), ('Thakur', 'Thakur'), ('Yadav', 'Yadav'), ('Others', 'Others')], max_length=100, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, choices=[('High School', 'High School'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('Doctorate', 'Doctorate'), ('Other', 'Other')], max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('Private Job', 'Private Job'), ('Government Job', 'Government Job'), ('Business', 'Business'), ('Self Employed', 'Self Employed'), ('Student', 'Student'), ('Not Working', 'Not Working')], max_length=100, null=True)),
                ('annual_income', models.CharField(blank=True, choices=[('Below 2 Lakh', 'Below 2 Lakh'), ('2-5 Lakh', '2-5 Lakh'), ('5-10 Lakh', '5-10 Lakh'), ('10-20 Lakh', '10-20 Lakh'), ('20 Lakh+', '20 Lakh+')], max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('working_city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, choices=[('India', 'India')], max_length=255, null=True)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('diet', models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Eggetarian', 'Eggetarian')], max_length=50, null=True)),
                ('smoking', models.CharField(blank=True, choices=[('No', 'No'), ('Occasionally', 'Occasionally'), ('Yes', 'Yes')], max_length=50, null=True)),
                ('drinking', models.CharField(blank=True, choices=[('No', 'No'), ('Occasionally', 'Occasionally'), ('Yes', 'Yes')], max_length=50, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=1000, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_occupation', models.CharField(blank=True, choices=[('Private Job', 'Private Job'), ('Government Job', 'Government Job'), ('Business', 'Business'), ('Self Employed', 'Self Employed'), ('Student', 'Student'), ('Not Working', 'Not Working')], max_length=255, null=True)),
                ('mother_occupation', models.CharField(blank=True, choices=[('Private Job', 'Private Job'), ('Government Job', 'Government Job'), ('Business', 'Business'), ('Self Employed', 'Self Employed'), ('Student', 'Student'), ('Not Working', 'Not Working')], max_length=255, null=True)),
                ('sisters', models.PositiveIntegerField(default=0)),
                ('brothers', models.PositiveIntegerField(default=0)),
                ('family_type', models.CharField(blank=True, choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], max_length=50, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('partner_preferences', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_image_upload_path)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('galary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('welcome', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interests', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interests', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
