# Generated by Django 5.1.3 on 2025-10-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_consultant',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_therapist',
        ),
    ]
