# Generated by Django 5.2.7 on 2025-11-02 16:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity_proof',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_identity_upload_path),
        ),
    ]
