# Generated by Django 5.1.3 on 2025-10-24 07:17

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccount_is_consultant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='medical_condition',
            new_name='about_me',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='annual_income',
            field=models.CharField(blank=True, choices=[('Below 2 Lakh', 'Below 2 Lakh'), ('2-5 Lakh', '2-5 Lakh'), ('5-10 Lakh', '5-10 Lakh'), ('10-20 Lakh', '10-20 Lakh'), ('20 Lakh+', '20 Lakh+')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Eggetarian', 'Eggetarian')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='drinking',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Occasionally', 'Occasionally'), ('Yes', 'Yes')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('Doctorate', 'Doctorate'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_type',
            field=models.CharField(blank=True, choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(choices=[('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Awaiting Divorce', 'Awaiting Divorce')], default='Never Married', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Private Job', 'Private Job'), ('Government Job', 'Government Job'), ('Business', 'Business'), ('Self Employed', 'Self Employed'), ('Student', 'Student'), ('Not Working', 'Not Working')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='partner_preferences',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Jain', 'Jain'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='siblings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smoking',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Occasionally', 'Occasionally'), ('Yes', 'Yes')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='working_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 60 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This may contain only letters, numbers, and @/./+/-/_ characters.', 'invalid')], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
