# Generated by Django 5.2.7 on 2025-11-10 10:33

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_post_by_alter_userprofile_annual_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='galary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_image', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_galary_image_upload_path),
        ),
    ]
