# Generated by Django 5.1.3 on 2025-10-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='father_occupation',
            field=models.CharField(blank=True, choices=[('Private Job', 'Private Job'), ('Government Job', 'Government Job'), ('Business', 'Business'), ('Self Employed', 'Self Employed'), ('Student', 'Student'), ('Not Working', 'Not Working')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mother_occupation',
            field=models.CharField(blank=True, choices=[('Private Job', 'Private Job'), ('Government Job', 'Government Job'), ('Business', 'Business'), ('Self Employed', 'Self Employed'), ('Student', 'Student'), ('Not Working', 'Not Working')], max_length=255, null=True),
        ),
    ]
