# Generated by Django 5.1.3 on 2025-10-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_userprofile_age_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='brothers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sisters',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
