# Generated by Django 5.1.3 on 2025-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_brothers_userprofile_hobbies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='partner_preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
