# Generated by Django 5.1.3 on 2025-10-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
