# Generated by Django 5.1.3 on 2025-11-01 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_premiumuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuser',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
