# Generated by Django 5.1.3 on 2025-11-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_premiumuser_expiry_date_alter_premiumuser_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumuser',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
