"""
Django settings for vivah project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=hb7u3u535our$$41tv2of3e&7uvsu59p(7vg&s3g@llevby4t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    # Default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_auth',
    'corsheaders',
    'allauth.socialaccount.providers.google',
    'rest_framework',
    'drf_yasg',
    'ckeditor',  # Ensure CKEditor is also added if not already
    'ckeditor_uploader',  # Include if you're using uploader
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    'dj_rest_auth.registration',
    'allauth.socialaccount',
    'django.contrib.sitemaps',
    # Your app
    'accounts',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vivah.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.views.navbar_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'vivah.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = "accounts.UserAccount"
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


SOCIALACCOUNT_PROVIDERS = {
     'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ),
}

REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'accounts.serializers.CustomRegisterSerializer',
}

REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'accounts.serializers.CustomUserDetailsSerializer',
    "LOGIN_SERIALIZER": "accounts.serializers.CustomLoginSerializer",
}

SITE_ID = 3
ACCOUNT_EMAIL_VERIFICATION = 'none'

CSRF_TRUSTED_ORIGINS = [
    "https://register.vivah.com"
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Razorpay Keys (replace with your actual keys)
RAZORPAY_KEY_ID = "rzp_live_EbyshVDVMkGLhW"
RAZORPAY_KEY_SECRET = "lNCdfCN3GOJpQZM77g3wFytG"
RAZORPAY_WEBHOOK_SECRET = "jY@7tM8MrYj8Gcb"
 
 
# RAZORPAY_KEY_ID = "rzp_test_wfGa9ofFKUmNwV"
# RAZORPAY_KEY_SECRET = "LsfazPxKhmsglxNY05Yknhak"
# RAZORPAY_WEBHOOK_SECRET = "test@rzp_web_qwert"

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


REST_USE_JWT = True
REST_AUTH_PW_RESET_USE_SITES_DOMAIN = True
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
JWT_AUTH_RETURN_EXPIRATION = True



from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True, # IMPORTANT
    'BLACKLIST_AFTER_ROTATION': True, # IMPORTANT
    'UPDATE_LAST_LOGIN': True,
}




REST_USE_JWT = True
JWT_AUTH_COOKIE = 'jwt-auth'  # Optional: For storing JWT in a cookie
JWT_AUTH_REFRESH_COOKIE = 'jwt-refresh-token'  # Optional: For refresh token in a cookie


REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'my-app-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'my-refresh-token',
    'REGISTER_SERIALIZER': 'accounts.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'accounts.serializers.CustomUserDetailsSerializer',
    "LOGIN_SERIALIZER": "accounts.serializers.CustomLoginSerializer",
    'JWT_AUTH_HTTPONLY': False,
}


import os
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Directory for collected static files during deployment
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Directory for additional static files
]


FCM_SERVER_KEY = "33a73a2108abdb3781e2bd474b962b313e7ed0f7"  # Replace with your Firebase server key

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    'https://5955c449dbef.ngrok-free.app',
]
CORS_ALLOW_ALL_ORIGINS = True

# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER='myvivahjourney@gmail.com'
EMAIL_HOST_PASSWORD='usvwxmgjoleishjn'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# EMAIL_HOST_USER='noreply@nityanava.com'
# EMAIL_HOST_PASSWORD='urkhqsczsrsxieyl'
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SMTP_ACCOUNTS = {
    'account1': {
        'HOST': 'smtp.gmail.com',
        'PORT': 587,
        'USERNAME': 'googelexam@gmail.com',
        'PASSWORD': 'guciwkuqkcmqasxb',
        'USE_TLS': True,
    },
    'account2': {
        'HOST': 'smtp.gmail.com',
        'PORT': 587,
        'USERNAME': 'googelexam@gmail.com',
        'PASSWORD': 'guciwkuqkcmqasxb',
        'USE_TLS': True,
    },
    'account3': {
        'HOST': 'smtp.gmail.com',
        'PORT': 587,
        'USERNAME': 'googelexam@gmail.com',
        'PASSWORD': 'guciwkuqkcmqasxb',
        'USE_TLS': True,
    }
}

CKEDITOR_UPLOAD_PATH = "uploads/ckeditor/"
import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# settings.py
APPEND_SLASH = True  # Recommended for REST APIs
