# Generated by Django 5.2.7 on 2025-11-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chandan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='date',
        ),
    ]
